# Generated by Django 5.1.4 on 2024-12-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genoma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sequencia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genes_pais', models.TextField(default='')),
                ('numero_geracoes', models.PositiveIntegerField()),
                ('resultado', models.TextField(blank=True, null=True)),
                ('estatisticas', models.JSONField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('grafico_base', models.TextField(default='')),
                ('genomas', models.ManyToManyField(to='simulacao.genoma')),
            ],
        ),
    ]
