# Generated by Django 5.1.4 on 2024-12-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulacao',
            name='grafico_base',
        ),
        migrations.AddField(
            model_name='simulacao',
            name='grafico_dados',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulacao',
            name='heredograma_dados',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
