# Generated by Django 5.1.4 on 2024-12-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao',
            name='estatisticas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
